# версия docker-compose
version: '3.7'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  mabot:
    image: ma_bot_image
    container_name: ma_bot
    build:
      context: .
      dockerfile: Dockerfile.ma_bot
    restart: always
    env_file:
      - ./.env
