# версия docker-compose
version: '3.7'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  mabot:
    image: ma_bot_image
    container_name: ma_bot
    build:
      context: .
      dockerfile: Dockerfile.ma_bot
    restart: always
    volumes:
      # Контейнер web будет работать с данными, хранящиеся в томе deals_data,
      # через свою директорию /app/deals_data/
      - deals_data:/ma_bot/deals_data/
    env_file:
      - ./.env
volumes:
  deals_data:
    external: true
