# версия docker-compose
version: '3.7'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  etcbot:
    image: etcbot_image
    container_name: etc_bot
    build:
      context: .
      dockerfile: Dockerfile.etc
    restart: always
    env_file:
      - ./.env
